bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# setting Ctrl + q for prefix key
unbind C-b
set-option -g prefix C-q
bind-key C-q send-prefix

set -g mouse on

# split panes using = and -
bind '=' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Use Meta + arrows to switch between panes
bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D
